//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ödev
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALINANMALLAR
    {
        public ALINANMALLAR()
        {
            this.STOKLAR = new HashSet<STOKLAR>();
        }
    
        public int Alinanmal_id { get; set; }
        public string Alinanmal_Ad { get; set; }
        public Nullable<int> Alinanmal_Mik { get; set; }
        public Nullable<System.DateTime> Alinanmal_Tarih { get; set; }
        public Nullable<System.DateTime> Alinanmal_SKT { get; set; }
    
        public virtual ICollection<STOKLAR> STOKLAR { get; set; }
    }
}
