//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ödev
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASALAR
    {
        public MASALAR()
        {
            this.SIPARISLER = new HashSet<SIPARISLER>();
        }
    
        public int Masa_id { get; set; }
        public string Masa_Ad { get; set; }
    
        public virtual ICollection<SIPARISLER> SIPARISLER { get; set; }
    }
}
