//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ödev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PASTANEİSLETMECİLİĞİEntities3 : DbContext
    {
        public PASTANEİSLETMECİLİĞİEntities3()
            : base("name=PASTANEİSLETMECİLİĞİEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALINANMALLAR> ALINANMALLAR { get; set; }
        public virtual DbSet<CALISANLAR> CALISANLAR { get; set; }
        public virtual DbSet<MASALAR> MASALAR { get; set; }
        public virtual DbSet<SIPARISLER> SIPARISLER { get; set; }
        public virtual DbSet<STOKLAR> STOKLAR { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
    }
}
