//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ödev
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISLER
    {
        public int Siparis_id { get; set; }
        public string Siparis_ad { get; set; }
        public Nullable<System.DateTime> Siparis_Tarih { get; set; }
        public Nullable<int> Urün_id { get; set; }
        public Nullable<int> Masa_id { get; set; }
        public Nullable<int> Calisan_id { get; set; }
    
        public virtual CALISANLAR CALISANLAR { get; set; }
        public virtual MASALAR MASALAR { get; set; }
        public virtual URUNLER URUNLER { get; set; }
    }
}
